services:

  db:
    image: postgres:17-alpine
    container_name: postgresdb

    environment:
      POSTGRES_DB: empresa
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@correo.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "8080:80"

    depends_on:
      - db

  app:
    build: .
    container_name: flaskapp

    ports:
      - "5000:5000"

    depends_on:
      - db

volumes:
  postgres_data: